
spring:
  application:
    name: breakin-application-api

  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
  sql:
    init:
      mode: embedded
      # To enable outbox events table, uncomment the following line:
      # schema-locations: classpath:schema.sql,classpath:schema-outbox.sql

  # Spring Data JDBC 설정
  data:
    jdbc:
      repositories:
        enabled: true

server:
  port: 8080

logging:
  level:
    dev.breakin: DEBUG
    org.springframework.jdbc: DEBUG
    org.springframework.jdbc.support: TRACE
    org.springframework.transaction: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

# Security 설정
breakin:
  security:
    # 로컬 테스트용 - 모든 경로 허용
    permit-all-paths:
      - /**

    # 프로덕션 설정 (주석 처리)
#    secure-all-paths: false
#    secured-path-pattern: /api/**
#    permit-all-paths:
#      - /api/auth/login
#      - /api/auth/signup
#      - /swagger-ui/**
#      - /api-docs/**
#      - /h2-console/**
