spring:
  application:
    name: breakin-application-batch

  datasource:
    url: jdbc:h2:mem:batchdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  sql:
    init:
      mode: embedded

server:
  port: 8081  # API 서버와 다른 포트

logging:
  level:
    dev.breakin: DEBUG
    org.springframework.scheduling: DEBUG
